version: "3.3"
services:
         user_auth:
              container_name: user_auth
              image: user_auth:latest
              ports:
                  - "5000:5000"
              restart: always
              build: .
              links:
                  - mongo
         mongo:
              container_name: mongo
              image: mongo:latest
              ports:
                  - "27017:27017"
              volumes:
                  - ./data:/data/db
